---
title: "SAP Crypto-HIV"
subtitle: "(selective overview)"
author: "Armin Rauschenberger"
date: '`r Sys.Date()`'
output:
  beamer_presentation:
    theme: "Madrid"
    colortheme: "dolphin"
    fonttheme: "structurebold"
classoption: "aspectratio=169"
editor_options: 
  chunk_output_type: console
header-includes:
  - \usepackage{xcolor}
  - \definecolor{darkblue}{RGB}{0,33,71}
  - \usepackage[justification=centering,labelformat=empty,font=small]{caption}
  - \setbeamercolor{palette primary}{bg=darkblue,fg=white}
  - \setbeamercolor{palette secondary}{bg=darkblue,fg=white}
  - \setbeamercolor{palette tertiary}{bg=darkblue,fg=white}
  - \setbeamercolor{structure}{fg=darkblue,bg=white}
  - \renewcommand\thefootnote{\textcolor{white}{\arabic{footnote}}}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(eval=TRUE,echo=FALSE)
```

## Randomisation

$$
\begin{array}{ccccccc}
\begin{array}{cc}
\text{RID} & \text{treatment} \\ \hline
101 & \color{red}{\text{SR}} \\
102 & \color{red}{\text{SR}} \\
103 & \color{blue}{\text{IR}} \\
104 & \color{blue}{\text{IR}} \\ \hline 
105 & \color{red}{\text{SR}} \\
106 & \color{blue}{\text{IR}} \\
107 & \color{red}{\text{SR}} \\
108 & \color{blue}{\text{IR}} \\ \hline
\vdots & \vdots
\end{array}
&
\quad
&
\begin{array}{cc}
\text{RID} & \text{treatment} \\ \hline
201 & \color{red}{\text{SR}} \\
202 & \color{blue}{\text{IR}} \\
203 & \color{blue}{\text{IR}} \\
204 & \color{red}{\text{SR}} \\ \hline 
205 & \color{blue}{\text{IR}} \\
206 & \color{red}{\text{SR}} \\
207 & \color{red}{\text{SR}} \\
208 & \color{blue}{\text{IR}} \\ \hline
\vdots & \vdots
\end{array}
&
\quad
&
\begin{array}{cc}
\text{RID} & \text{treatment} \\ \hline
301 & \color{blue}{\text{IR}} \\
302 & \color{red}{\text{SR}} \\
303 & \color{blue}{\text{IR}} \\
304 & \color{red}{\text{SR}} \\ \hline 
305 & \color{blue}{\text{IR}} \\
306 & \color{blue}{\text{IR}} \\
307 & \color{red}{\text{SR}} \\
308 & \color{red}{\text{SR}} \\ \hline
\vdots & \vdots
\end{array}
&
\quad
&
\cdots
\end{array}
$$

- immediate-release (\textcolor{red}{IR}, 4 doses) vs sustained-release (\textcolor{blue}{SR}, 2 doses)

- randomisation in blocks of 4 for each hospital

- 72 participants (at least \textcolor{red}{33}+\textcolor{blue}{33}=66 evaluable participants)

## PK - schedule

$$
\begin{array}{r|ccccc}
 & \text{day}~1 & \text{days}~2-5 & \text{day}~6 & \text{days}~7-14 & \text{day}~15 \\ \hline
\text{doses} & {\color{red}{4}}~\text{or}~{\color{blue}{2}} & {\color{red}{4}}~\text{or}~{\color{blue}{2}} & {\color{red}{4}}~\text{or}~{\color{blue}{2}} & {\color{red}{4}}~\text{or}~{\color{blue}{2}} & -\\
\text{data} & 7 & - & 7 & - &  1 \\ \hline
& \text{AUC}_{{\color{red}{\text{IR}}}/{\color{blue}{\text{SR}}},1} & - & \text{AUC}_{{\color{red}{\text{IR}}}/{\color{blue}{\text{SR}}},6} & - & -  
\end{array}
$$

$~$

- \textcolor{red}{4} or \textcolor{blue}{2} drug administrations per day

- AUC on day 1 for 12 hours (\textcolor{red}{2} vs \textcolor{blue}{1} doses, 1 pre-dose + 5 post-dose measurements)

- comparison of AUC between \textcolor{red}{IR} and \textcolor{blue}{SR} on day 1

## PK - model

$$
\log\text{AUC}_{i} = \alpha + \beta \times \mathbb{I}[\text{treatment}_i={\color{blue}{\text{SR}}}] + \alpha_j + \epsilon_{i}
$$

$$
\begin{array}{l}
\text{where} \quad i \in \{1,\ldots,72\} \quad (\text{patient}) \\
\phantom{where} \quad j \in \{1,2,3,\ldots\} \quad (\text{hospital})
\end{array}
$$

$$
H_0: \beta \leq -\delta ~\cup~ \delta \leq \beta \qquad \text{vs} \qquad H_1: - \delta < \beta < \delta
$$

$~$

- aim: find evidence for equivalence ($\text{AUC}_{\color{blue}{\text{SR}}} \approx \text{AUC}_{\color{red}{\text{IR}}}$)

- alternative: two one-sided two-sample $t$-tests

<!--
combined model for both days
$$
\log\text{AUC}_{i,t} = \alpha + \beta \times \mathbb{I}[\text{treatment}_i=\text{SR}] + \gamma \times \mathbb{I}[\text{day}_{i,t}=6] + \alpha_i + \epsilon_{i,t}
$$

$$
\begin{array}{l}
\text{where} \quad i \in \{1,\ldots,72\} \quad (\text{patient}) \\
\phantom{where} \quad t \in \{1,2\} \quad (\text{time})
\end{array}
$$

$$
H_0: \beta \leq -\delta ~\cup~ \delta \leq \beta \qquad \text{vs} \qquad H_1: - \delta < \beta < \delta
$$

Assumption: Difference between SR and IR is constant over time (i.e., same on days 1 and 6).
-->

## EFA - schedule

$$
\begin{array}{r|ccccccc}
 & \text{day}~1 & \text{day}~2 & \text{day}~3 & \text{days}~4-6 & \text{day}~7 & \text{day}~8-14 & \text{day}~15 \\ \hline
\text{doses} & {\color{red}{4}}~\text{or}~{\color{blue}{2}} & {\color{red}{4}}~\text{or}~{\color{blue}{2}} & {\color{red}{4}}~\text{or}~{\color{blue}{2}} & {\color{red}{4}}~\text{or}~{\color{blue}{2}} & {\color{red}{4}}~\text{or}~{\color{blue}{2}} & {\color{red}{4}}~\text{or}~{\color{blue}{2}} & - \\
\text{data} & 1 & - & 1 & - &  1 & - & 1 \\ \hline
& \text{CFU}_{{\color{red}{\text{IR}}}/{\color{blue}{\text{SR}}},1} & - & \text{CFU}_{{\color{red}{\text{IR}}}/{\color{blue}{\text{SR}}},3} & - & \text{CFU}_{{\color{red}{\text{IR}}}/{\color{blue}{\text{SR}}},7} & - & \text{CFU}_{{\color{red}{\text{IR}}}/{\color{blue}{\text{SR}}},15}
\end{array}
$$

$~$

- measurement of colony forming units (CFU) on 4 days

- comparison of CFU between \textcolor{red}{IR} and \textcolor{blue}{SR}

## EFA - model

$$
\mathrm{log10}~\text{CFU}_{i,t} = \alpha + \beta \times \mathbb{I}[\text{treatment}_i={\color{blue}{\text{SR}}}] + \gamma \times \text{day}_{i,t} + \alpha_i + \epsilon_{i,t}
$$
$$
\begin{array}{l}
\text{where} \quad i \in \{1,\ldots,72\} \quad (\text{patient}) \\
\phantom{where} \quad t \in \{1,2,3,4\} \quad (\text{time})
\end{array}
$$

$$
H_0: \beta \leq - \delta \qquad \text{vs} \qquad H_1: \beta > -\delta 
$$

$~$

- aim: find evidence for non-inferiority ($\text{CFU}_{\color{blue}{\text{SR}}} \gtrsim \text{CFU}_{\color{red}{\text{IR}}}$)

- assumption: linear decrease/increase with respect to time

- assumption: constant difference between IR and SR over time

## Multiplicity

$$
\begin{array}{cc}
\begin{array}{l}
\text{co-primary endpoints:} \\
\text{significance required for \textit{both} endpoints} \\
\Rightarrow \text{no multiple-testing correction}
\end{array}
&
\begin{array}{l}
\text{two primary endpoints:} \\
\text{significance required for \textit{one} endpoint} \\
\Rightarrow \text{multiple-testing correction} \\
\end{array}
\\
~ \hspace{3cm} \huge\color{red}{\boldsymbol{\times}} \hspace{3cm} ~
&
~ \hspace{3cm} \huge\color{green}{\boldsymbol{\checkmark}} \hspace{3cm} ~
\end{array}
$$
$~$

$~$

$$
\begin{array}{cc}
\begin{array}{l}
\text{Bonferroni-correction:} \\
max(p_{\text{AUC,above}},p_{\text{AUC,below}}) \leq 2.5\% \\
p_{\text{CFU,above}} \leq 1.25\% \\
\end{array}
&
\begin{array}{l}
\text{Bonferroni-Holm correction:} \\
\Rightarrow \text{adaptive significance levels} \\
\phantom{-}
\end{array}
\\
~ \hspace{3cm} \huge\color{red}{\boldsymbol{\times}} \hspace{3cm} ~
&
~ \hspace{3cm} \huge\color{green}{\boldsymbol{\checkmark}} \hspace{3cm} ~
\end{array}
$$

## Bonferroni-Holm correction

- IF $max(p_{\text{AUC,above}},p_{\text{AUC,below}})$ < $2 \times p_{\text{CFU,above}}$

  - IF $max(p_{\text{AUC,above}},p_{\text{AUC,below}}) \leq 2.5\%$ THEN
  
    - "PK equivalence" ($\text{AUC}_{\color{blue}{\text{SR}}} \approx \text{AUC}_{\color{red}{\text{IR}}}$)
    
    - IF $p_{\text{CFU,above}} \leq 2.5\%$ THEN "EFA non-inferiority"
    
  - ELSE "failure"
    
$~$
        
- IF $max(p_{\text{AUC,above}},p_{\text{AUC,below}})$ > $2 \times p_{\text{CFU,above}}$

  - IF $p_{\text{CFU,above}} \leq 1.25\%$ THEN
  
    - "EFA non-inferiority" ($\text{CFU}_{\color{blue}{\text{SR}}} \gtrsim \text{CFU}_{\color{red}{\text{IR}}}$)
    
    - IF $max(p_{\text{AUC,above}},p_{\text{AUC,below}}) \leq 5\%$ THEN "PK equivalence"
    
  - ELSE "failure"
  
<!--
testing with CI: 95\%, 95\%; 97.5\%, 90\%  
-->

## Summary

- stratified blocked randomisation

$~$

- PK equivalence ($\text{AUC}_{\color{blue}{\text{SR}}} \approx \text{AUC}_{\color{red}{\text{IR}}}$)

$~$

- EFA non-inferiority ($\text{CFU}_{\color{blue}{\text{SR}}} \gtrsim \text{CFU}_{\color{red}{\text{IR}}}$)
  
$~$

- Bonferroni-Holm correction

<!--
SAP Crypto-HIV (selective overview)

randomisation: stratified blocked randomisation, randomisation for each hospital separately, randomisation with permuted blocks of size 4, small and fixed block size so that hospitals with slow recruitment can easily complete their last block; sample size calculation requires 18 completed blocks (18 x 4 = 72 participants), allowing for 3 non-evaluable participants in each treatment arm; there are two primary endpoints, one for pharmacokinetics and one for early fungicidal acticity

PK - schedule: pharmacokinetics (PK); participants will receive 4 doses (reference treatment “immediate-release”) or 2 doses (experimental treatment “sustained-release”) per day during two weeks; drug plasma concentrations will be measured 7 times on day 1, 7 times on day 6, and once on day 15; after each dose, we expect first a sharp increase and then a flat decrease of the concentration, but this will not be visible in a graph as there are too few measurements; the area under the concentration curve will be calculated for days 1 and 6 separately; only the AUC on day 1 is a primary endpoint; AUC on day 1 (based on 7 measurements) will be compared between the two treatment groups

PK - model: linear mixed model to compare the AUC between the two treatment groups; log-transformation of the AUC, fixed intercept, fixed effect for the treatment (SR vs IR), random effect for the hospital; test the null hypothesis that the effect of the experimental treatment (i.e., different with respect to the reference treatment) is smaller than minus delta or larger than plus delta against the alternative hypothesis that the effect is between minus and plus delta; this involves two one-sided hypothesis tests;  the aim is to find evidence for bioequivalence (i.e., the AUC is more or less the same for SR and IR); if the random effect for the hospital is not needed, this can also be done with two one-sided two-sample t-tests

EFA - schedule: early fungicidal activity (EFA); colony forming units (CFU) in the cerebrospinal fluid (CSF) will be measured on four days (day 1, 3, 7 and 15); the aim is to compare CFU between the two treatment groups

EFA - model: linear mixed model to compare CFU between the two treatment groups; log10 transformation for CFU, fixed intercept, fixed effect of experimental treatment (SR) as compared to reference treatment (IR), fixed effect for time, random intercept for the participant (each participant is measured at four time points); test the null hypothesis that the effect is is below minus delta against the alternative hypothesis that the effect is above  minus delta; the aim is to find evidence for non-inferiority; this model assumes (among other things) that the decrease/increase in CFU is linear with respect to time and that there is a constant difference between the two treatments over time

multiplicity: The aim is to control the family-wise error rate at 5% (i.e., the probability of making at least one false discovery). In the case of co-primary endpoints, significance is required for both endpoints. Then no multiple testing correction is needed. But here we have two primary endpoints, where significance is required for at least one endpoint (PK, EFA, or both). So multiple testing correction is needed. If we used the Bonferroni correction, we would split the 5% level into two for the two primary endpoints. For PK, this leads to a 2.5% level (two one-sided test but intersection-union principle). For EFA, this leads to a 1.25% level (2.5% divided by two sides). The Bonferroni-Holm correction is superior (leading to a higher statistical power) but has adaptive significance levels.

Bonferroni-Holm correction: First, we compare the Bonferroni-adjusted p-values (times 2 for PK, times 4 for EFA). First scenario: PK is more significant, we first test PK at the 2.5% level (two remaining comparisons), and then - if PK is significant - EFA at the 2.5% level (one remaining comparison but one-sided test). Second scenario: EFA is more significant, we first test EFA at the 1.25% level (two remaining comparisons and one-sided test), and then - if EFA is significant - PK at the 5% level (one remaining comparison). If one of the two p-values is significant, the clinical trial is a success.

summary: This was a selective overview of the statistical analysis plan. Stratified blocked randomisation will be used to assign the participants to the two treatment groups. There are two primary endpoints. The aims is to detect PK bioequivalence (approximately equal AUCs) and EFA non-inferiority (higher or approximately equal CFU). The Bonferroni-Holm procedure will be used for multiplicity adjustment.
-->
